name: Build & Publish

on:
  push:
    branches:
      - root

    paths-ignore:
      - "yaml-files/**"

  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1

        with:
          java-version: 1.17

      - name: Gradle (Build)
        uses: gradle/gradle-build-action@v2

        with:
          arguments: build
          dependency-graph: generate-and-submit

        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Upload artifacts (Main JAR)
        uses: actions/upload-artifact@v2

        with:
          name: Main JAR
          path: build/libs/*-all.jar

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2

        with:
          name: JARs
          path: build/libs/*.jar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker containers

        run: |
          docker build -t ghcr.io/cmc-discord/bot-general:latest -t ghcr.io/cmc-discord/bot-general:${GITHUB_SHA} .

          docker push ghcr.io/cmc-discord/bot-general:latest
          docker push ghcr.io/cmc-discord/bot-general:${GITHUB_SHA}
